# Automatic IPE block for autoCAD
This is a begginer's project written in python using pyautocad library. It generates an autoCAD block with the selected IPE steel beam.

# USAGE:
To use it you only need to have your desired autoCAD file opened, then execute the code. The program opens the console and asks for the height/name of the beam.

The script generates an autoCAD block with the name of the beam and zooms to it.

# 19 sep 2025
Modified the code with "jimtk" reddit user's help, adding functions, using polylines instead of line segments and making more legible code.

Also added more beam types.
